// Global ID & Age Verification Breach Tracker — main.js (v10)
// Master data plus reviewed research batches are merged client-side by ID.
const DATA_PATHS = { breaches:'data/breaches.json', companies:'data/companies.json', sources:'data/sources.json', supplemental:'data/supplemental-data.json' };
const _cache = {};
async function loadJson(path) { if (_cache[path]) return _cache[path]; try { const res = await fetch(path,{cache:'no-store'}); if(!res.ok)return null; const data=await res.json(); _cache[path]=data; return data; } catch(e){return null;} }
function dedupeById(items) { const map=new Map(); items.forEach(item=>{if(item&&item.id)map.set(item.id,item)}); return [...map.values()]; }
async function loadData(key) {
  if (key==='breaches'||key==='companies') { const [main, supplement]=await Promise.all([loadJson(DATA_PATHS[key]),loadJson(DATA_PATHS.supplemental)]); const field=key; return {[field]:dedupeById([...(main?.[field]||[]),...(supplement?.[field]||[])])}; }
  const data=await loadJson(DATA_PATHS[key]); if(!data)throw new Error('Failed to load '+key); return data;
}
function escapeHtml(str){return str===undefined||str===null?'':String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function formatDate(iso){try{return new Date(iso+'T00:00:00Z').toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'})}catch(e){return iso}}
function titleCase(str){return String(str).replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function severityBadge(sev){const cls={low:'badge-low',medium:'badge-medium',high:'badge-high',critical:'badge-critical'}[sev]||'badge-medium';return `<span class="badge ${cls}">${escapeHtml(titleCase(sev))}</span>`}
function companyNameById(companies,id){return companies.find(c=>c.id===id)?.name||id}
async function initHomepage(){const statsEl=document.getElementById('home-stats'),timelineEl=document.getElementById('home-timeline');if(!statsEl&&!timelineEl)return;try{const[{breaches},{companies}]=await Promise.all([loadData('breaches'),loadData('companies')]);if(statsEl){const latest=breaches.reduce((a,b)=>!a||b.date>a.date?b:a,null);statsEl.innerHTML=`<div class="stat-card"><span class="stat-value">${breaches.length}</span><span class="stat-label">Tracked breaches</span></div><div class="stat-card"><span class="stat-value">${companies.length}</span><span class="stat-label">Monitored companies &amp; services</span></div><div class="stat-card"><span class="stat-value">${latest?formatDate(latest.date):'—'}</span><span class="stat-label">Most recent known breach</span></div>`}if(timelineEl){timelineEl.innerHTML=[...breaches].sort((a,b)=>a.date<b.date?1:-1).slice(0,6).map(b=>`<div class="timeline-item"><div class="timeline-date">${formatDate(b.date)}</div><div class="timeline-title"><a href="breaches.html#${escapeHtml(b.id)}">${escapeHtml(b.title)}</a> ${severityBadge(b.severity)}</div><p>${escapeHtml(b.summary)}</p></div>`).join('')}}catch(e){if(statsEl)statsEl.innerHTML='<p class="empty-state">Data is currently unavailable. Please try again later.</p>';console.error(e)}}
let _allBreaches=[],_allCompanies=[];
function sortBreaches(items,key){const rank={low:0,medium:1,high:2,critical:3};return [...items].sort((a,b)=>{if(key==='date-asc')return a.date<b.date?-1:a.date>b.date?1:0;if(key==='severity-desc')return rank[b.severity]-rank[a.severity];if(key==='title-asc')return a.title.localeCompare(b.title);return a.date<b.date?1:a.date>b.date?-1:0})}
async function initBreachesPage(){if(!document.getElementById('breach-list'))return;const[{breaches},{companies}]=await Promise.all([loadData('breaches'),loadData('companies')]);_allBreaches=breaches;_allCompanies=companies;populateFilterOptions(breaches,companies);['filter-region','filter-severity','filter-company','filter-datatype','filter-sort'].forEach(id=>document.getElementById(id).addEventListener('change',applyBreachFilters));document.getElementById('filter-search').addEventListener('input',applyBreachFilters);applyBreachFilters();if(location.hash){const t=document.querySelector(location.hash);if(t){const d=t.querySelector('details');if(d)d.open=true;t.scrollIntoView({behavior:'smooth',block:'start'})}}}
function populateFilterOptions(breaches,companies){const add=(id,values,label)=>{const el=document.getElementById(id);values.forEach(v=>el.insertAdjacentHTML('beforeend',`<option value="${escapeHtml(v)}">${escapeHtml(label(v))}</option>`))};add('filter-region',[...new Set(breaches.flatMap(b=>b.affected_regions))].sort(),titleCase);add('filter-company',[...new Set(breaches.flatMap(b=>b.companies))].sort(),id=>companyNameById(companies,id));add('filter-datatype',[...new Set(breaches.flatMap(b=>b.data_types))].sort(),titleCase)}
function applyBreachFilters(){const region=document.getElementById('filter-region').value,severity=document.getElementById('filter-severity').value,company=document.getElementById('filter-company').value,dataType=document.getElementById('filter-datatype').value,sort=document.getElementById('filter-sort').value||'date-desc',search=document.getElementById('filter-search').value.trim().toLowerCase();const filtered=_allBreaches.filter(b=>(!region||b.affected_regions.includes(region))&&(!severity||b.severity===severity)&&(!company||b.companies.includes(company))&&(!dataType||b.data_types.includes(dataType))&&(!search||(b.title+' '+b.summary+' '+b.details).toLowerCase().includes(search)));renderBreachList(sortBreaches(filtered,sort),_allCompanies)}
function renderBreachList(breaches,companies){const list=document.getElementById('breach-list'),count=document.getElementById('breach-count');if(count)count.textContent=`${breaches.length} breach${breaches.length===1?'':'es'}`;if(!breaches.length){list.innerHTML='<p class="empty-state">No breaches match your filters. Try broadening your search.</p>';return}list.innerHTML=breaches.map(b=>{const companyLinks=b.companies.map(id=>{const c=companies.find(x=>x.id===id);return c?`<a href="companies.html#${escapeHtml(c.id)}">${escapeHtml(c.name)}</a>`:escapeHtml(id)}).join(', ');const data=b.data_types.map(x=>`<li>${escapeHtml(titleCase(x))}</li>`).join('');const regions=b.affected_regions.map(x=>`<span class="badge badge-region">${escapeHtml(titleCase(x))}</span>`).join(' ');const sources=b.sources.map(s=>`<li><a href="${escapeHtml(s)}" target="_blank" rel="noopener noreferrer">${escapeHtml(new URL(s).hostname.replace('www.',''))}</a></li>`).join('');return `<article class="breach-card" id="${escapeHtml(b.id)}"><div class="breach-card-top"><h3>${escapeHtml(b.title)}</h3>${severityBadge(b.severity)}</div><div class="breach-meta"><span class="badge badge-type">${escapeHtml(titleCase(b.verification_type))}</span>${regions}<span class="timeline-date">${formatDate(b.date)}</span></div><p class="summary">${escapeHtml(b.summary)}</p><p><strong>Companies involved:</strong> ${companyLinks||'Unspecified'}</p><ul class="data-types-list">${data}</ul><details><summary>Full details &amp; sources</summary><p>${escapeHtml(b.details)}</p><p><strong>Sources:</strong></p><ul class="source-list">${sources}</ul></details></article>`}).join('')}
async function initCompaniesPage(){if(!document.getElementById('company-list'))return;const[{companies},{breaches}]=await Promise.all([loadData('companies'),loadData('breaches')]);_allCompanies=companies;_allBreaches=breaches;const add=(id,items)=>{const el=document.getElementById(id);items.forEach(x=>el.insertAdjacentHTML('beforeend',`<option value="${escapeHtml(x)}">${escapeHtml(titleCase(x))}</option>`))};add('filter-company-region',[...new Set(companies.map(c=>c.region))].sort());add('filter-company-type',[...new Set(companies.map(c=>c.type))].sort());renderCompanyList(companies,breaches);document.getElementById('filter-company-region').addEventListener('change',applyCompanyFilters);document.getElementById('filter-company-type').addEventListener('change',applyCompanyFilters);document.getElementById('filter-company-search').addEventListener('input',applyCompanyFilters)}
function applyCompanyFilters(){const region=document.getElementById('filter-company-region').value,type=document.getElementById('filter-company-type').value,search=document.getElementById('filter-company-search').value.trim().toLowerCase();renderCompanyList(_allCompanies.filter(c=>(!region||c.region===region)&&(!type||c.type===type)&&(!search||(c.name+' '+c.description).toLowerCase().includes(search))),_allBreaches)}
function renderCompanyList(companies,breaches){const list=document.getElementById('company-list'),count=document.getElementById('company-count');if(count)count.textContent=`${companies.length} compan${companies.length===1?'y':'ies'}`;if(!companies.length){list.innerHTML='<p class="empty-state">No companies match your filters.</p>';return}list.innerHTML=companies.map(c=>{const related=breaches.filter(b=>b.companies.includes(c.id));const links=related.map(b=>`<li><a href="breaches.html#${escapeHtml(b.id)}">${escapeHtml(b.title)}</a> (${formatDate(b.date)})</li>`).join('');return `<article class="card company-card" id="${escapeHtml(c.id)}"><div class="company-badges"><span class="badge badge-region">${escapeHtml(titleCase(c.region))}</span><span class="badge badge-type">${escapeHtml(titleCase(c.type))}</span></div><h3><a href="${escapeHtml(c.website)}" target="_blank" rel="noopener noreferrer">${escapeHtml(c.name)}</a></h3><p>${escapeHtml(c.description)}</p>${c.notes?`<p><em>${escapeHtml(c.notes)}</em></p>`:''}<p class="breach-count ${related.length?'':'none'}">${related.length?related.length+' known breach'+(related.length===1?'':'es'):'No known breaches'}</p>${related.length?`<ul class="source-list">${links}</ul>`:''}<p class="company-link"><a href="${escapeHtml(c.website)}" target="_blank" rel="noopener noreferrer">Visit official website ↗</a></p></article>`}).join('')}
const THEME_KEY='id-breach-tracker-theme';function getCurrentTheme(){return document.documentElement.getAttribute('data-theme')==='dark'?'dark':'light'}function updateThemeToggleUI(theme){const b=document.getElementById('theme-toggle');if(!b)return;b.setAttribute('aria-pressed',theme==='dark'?'true':'false');b.setAttribute('aria-label',theme==='dark'?'Switch to light mode':'Switch to dark mode');b.setAttribute('title',theme==='dark'?'Switch to light mode':'Switch to dark mode');b.textContent=theme==='dark'?'☀':'☾'}function initThemeToggle(){updateThemeToggleUI(getCurrentTheme());const b=document.getElementById('theme-toggle');if(!b)return;b.addEventListener('click',()=>{const t=getCurrentTheme()==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',t);try{localStorage.setItem(THEME_KEY,t)}catch(e){}updateThemeToggleUI(t)})}
document.addEventListener('DOMContentLoaded',()=>{initThemeToggle();initHomepage();initBreachesPage();initCompaniesPage();const y=document.getElementById('footer-year');if(y)y.textContent=new Date().getFullYear()});
